server:
  port: 8001

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/attendance_management?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: root
  thymeleaf:
    mode: HTML
    #禁用缓存
    cache: false
  #绑定国际化配置文件
  messages:
    encoding: UTF-8
    basename: i18n.login


mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*Mapper.xml
  type-aliases-package: ncu.huaxin.attendancemanagement.entity

logging:
  level:
    main.blog.mapper: trace

